/*customer stored procedures*/
USE [MMABooksUpdated]
GO
/****** Object:  StoredProcedure [dbo].[usp_ProductCreate]    Script Date: 11/21/2018 1:01:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/***************Create************************************************/

alter PROCEDURE [dbo].[usp_CustomerCreate] 
	-- Add the parameters for the stored procedure here
	@CustomerID int output, /* output parameter is generated by DB*/
	@Name varchar(100), 
	@Address varchar(50), 	
	@City varchar(20),
	@State char(2),
	@Zipcode char(15)
	

AS
BEGIN
    -- Insert statements for procedure here
	Insert into Customers(CustomerID, Name, Address, City, State, ZipCode, ConcurrencyID)
	values (@CustomerID, @Name, @Address, @City,@State,@Zipcode, 1);
	set @CustomerID = @@IDENTITY;/*assigment statement @@Identity is global thing that corresponds to auto#*/
END

/*****Delete*****/

GO

CREATE PROCEDURE [dbo].[usp_CustomerDelete] 
	-- Add the parameters for the stored procedure here
	@CustomerID int, @ConcurrencyID int
AS
BEGIN
    -- Insert statements for procedure here
	Delete from Products where ProductID = @CustomerID and ConcurrencyID = @ConcurrencyID;
END

go
/*****Select*****/

CREATE PROCEDURE [dbo].[usp_CustomerSelect] 
@CustomerID int
AS
BEGIN
    select * from Customers 
	where CustomerID = @CustomerID;
END


/*****update*****/
CREATE PROCEDURE [dbo].[usp_CustomerUpdate] 
	-- Add the parameters for the stored procedure here
	@CustomerID int,
	@Name varchar(100),
	@Address varchar(50), 
	@City varchar(20), 
	@State char(2), 
	@ConcurrencyID int
AS
BEGIN
    -- Insert statements for procedure here
	Update Customers set
		@CustomerID = @CustomerID,
		Name = @Name, 
		Address = @Address,
		City = @City,
		State=@State,
		ConcurrencyID = (@ConcurrencyID + 1)
	Where CustomerID = @CustomerID and ConcurrencyID = @ConcurrencyID; /*stops updates if ID and Concurrency ID dont match. also updates CCID*/

END

go

/*****SelectAll*****/
CREATE PROCEDURE [dbo].[usp_CustomerSelectAll] 
	-- Add the parameters for the stored procedure here
AS
BEGIN
    -- Insert statements for procedure here
	SELECT * from Customers order by CustomerID;
END

